export const metalCabinets = {
  name: "Шкаф металлический",
  titles: [
    { items_type: "Тип" },
    { items_model: "Модель" },
    { items_depth: "Глубина, см" },
    { items_width: "Ширина, см" },
    { items_height: "Высота шкафа, см" },
    { items_sections: "Количество секций" },
    { items_shelves: "Количество полок" },
    { items_drawer: "Количество ящиков" },
    { items_set: "Комплектация" },
    { itemsQnt: "Количество шкафов" },
    { addShelfPriceQnt: "Количество дополнительных полок" },
  ],
  items: [
    {
      model: "ШРМ-АК/500",
      type: "для одежды",
      depth: 500,
      width: 500,
      height: 1860,
      sections: 2,
      shelves: 2,
      drawer: "нет",
      set: "2 перекладины, 4 крючка, 2 верзных замка",
      addShelfPrice: 11,
      price: 100,
    },
    {
      model: "ШРМ-АК-У",
      type: "для одежды",
      depth: 500,
      width: 500,
      height: 1860,
      sections: 1,
      shelves: 3,
      drawer: "нет",
      set: "1 перекладина, 2 крючка, 1 верзной замок",
      addShelfPrice: 10,
      price: 200,
    },
    {
      model: "ШРМ-АК",
      type: "для одежды",
      depth: 500,
      width: 600,
      height: 1860,
      sections: 2,
      shelves: 2,
      drawer: "нет",
      set: "2 перекладины, 4 крючка, 2 верзных замка",
      addShelfPrice: 9,
      price: 300,
    },
    {
      model: "ШРМ-АК/800",
      type: "для одежды",
      depth: 500,
      width: 800,
      height: 1860,
      sections: 2,
      shelves: 2,
      drawer: "нет",
      set: "2 перекладины, 4 крючка, 2 верзных замка",
      addShelfPrice: 4,
      price: 400,
    },
    {
      model: "ШРМ-22",
      type: "для одежды",
      depth: 500,
      width: 600,
      height: 1860,
      sections: 2,
      shelves: 2,
      drawer: "нет",
      set: "2 перекладины, 4 крючка, 2 верзных замка",
      addShelfPrice: 18,
      price: 400,
    },
    {
      model: "ШРМ-22/800",
      type: "для одежды",
      depth: 500,
      width: 600,
      height: 1860,
      sections: 2,
      shelves: 2,
      drawer: "нет",
      set: "2 перекладины, 4 крючка, 2 верзных замка",
      addShelfPrice: 12,
      price: 412,
    },
    {
      model: "ШРМ-33",
      type: "для одежды",
      depth: 500,
      width: 900,
      height: 1860,
      sections: 3,
      shelves: 3,
      drawer: "нет",
      set: "3 перекладины, 6 крючков, 3 верзных замка",
      addShelfPrice: 7,
      price: 450,
    },
    {
      model: "ШРМ-11",
      type: "для одежды",
      depth: 500,
      width: 300,
      height: 1860,
      sections: 1,
      shelves: 1,
      drawer: "нет",
      set: "1 перекладина, 2 крючка, 1 верзной замок",
      addShelfPrice: 11,
      price: 422,
    },
    {
      model: "ШРМ-11/400",
      type: "для одежды",
      depth: 500,
      width: 400,
      height: 1860,
      sections: 1,
      shelves: 1,
      drawer: "нет",
      set: "1 перекладина, 2 крючка, 1 верзной замок",
      addShelfPrice: 5,
      price: 422,
    },
    {
      model: "ШРМ-12",
      type: "для одежды",
      depth: 500,
      width: 300,
      height: 1860,
      sections: "2 отделения",
      shelves: 1,
      drawer: "нет",
      set: "1 перекладина, 2 крючка, 1 верзной замок",
      addShelfPrice: 13,
      price: 422,
    },
    {
      model: "ШРМ-22М",
      type: "для одежды",
      depth: 500,
      width: 600,
      height: 1860,
      sections: 2,
      shelves: 1,
      drawer: "нет",
      set: "2 перекладины, 4 крючка, 2 верзной замок",
      addShelfPrice: 22,
      price: 422,
    },
    {
      model: "ШРМ-22М/800",
      type: "для одежды",
      depth: 500,
      width: 800,
      height: 1860,
      sections: 1,
      shelves: 1,
      drawer: "нет",
      set: "2 перекладины, 4 крючка, 2 верзной замок",
      addShelfPrice: 15,
      price: 422,
    },
    {
      model: "ШРМ-М",
      type: "для одежды",
      depth: 500,
      width: 300,
      height: 1860,
      sections: 1,
      shelves: 1,
      drawer: "нет",
      set: "1 перекладина, 2 крючка, 1 верзной замок",
      addShelfPrice: 14,
      price: 422,
    },
    {
      model: "ШРМ-М/400",
      type: "для одежды",
      depth: 500,
      width: 400,
      height: 1860,
      sections: 1,
      shelves: 1,
      drawer: "нет",
      set: "1 перекладина, 2 крючка, 1 верзной замок",
      addShelfPrice: 10,
      price: 422,
    },
    {
      model: "ШРМ-21",
      type: "для одежды",
      depth: 500,
      width: 400,
      height: 1860,
      sections: "2 отделения",
      shelves: 1,
      drawer: "нет",
      set: "2 перекладины, 4 крючка, 1 верзной замок",
      addShelfPrice: 21,
      price: 422,
    },
    {
      model: "ШРМ-22У",
      type: "для одежды",
      depth: 500,
      width: 600,
      height: 1860,
      sections: 2,
      shelves: 5,
      drawer: "нет",
      set:
        "в одной секции: полка для головного убора, 1 перекладина, 2 крючка, замок в другой 4 регулируемые полки, замок",
      addShelfPrice: 22,
      price: 422,
    },
    {
      model: "ШРМ-22/800У",
      type: "для одежды",
      depth: 500,
      width: 800,
      height: 1860,
      sections: 2,
      shelves: 5,
      drawer: "нет",
      set:
        "в одной секции: полка для головного убора, 1 перекладина, 2 крючка, замок в другой 4 регулируемые полки, замок",
      addShelfPrice: 13,
      price: 422,
    },
    {
      model: "ШРМ-24",
      type: "для одежды",
      depth: 500,
      width: 600,
      height: 1860,
      sections: "4 отделения",
      shelves: 1,
      drawer: "нет",
      set: "4 перекладины, 8 крючков, 4 верзных замка",
      addShelfPrice: 13,
      price: 422,
    },
    {
      model: "ШАМ-11",
      type: "бухгалтерский",
      depth: 500,
      width: 850,
      height: 1860,
      sections: 1,
      shelves: 1,
      drawer: "нет",
      set: "ригельный замок, фиксатор",
      addShelfPrice: 21,
      price: 100,
    },
    {
      model: "ШАМ-11/920",
      type: "бухгалтерский",
      depth: 500,
      width: 850,
      height: 1860,
      sections: 1,
      shelves: 3,
      drawer: "нет",
      set: "ригельный замок, фиксатор",
      addShelfPrice: 15,
      price: 200,
    },
    {
      model: "ШАМ-11/400",
      type: "бухгалтерский",
      depth: 400,
      width: 850,
      height: 1860,
      sections: 1,
      shelves: 3,
      drawer: "нет",
      set: "ригельный замок, фиксатор",
      addShelfPrice: 14,
      price: 200,
    },
    {
      model: "ШАМ-11/600",
      type: "бухгалтерский",
      depth: 500,
      width: 600,
      height: 1860,
      sections: 1,
      shelves: 3,
      drawer: "нет",
      set: "ригельный замок, фиксатор",
      addShelfPrice: 24,
      price: 200,
    },
    {
      model: "ШАМ-11/20",
      type: "бухгалтерский",
      depth: 500,
      width: 850,
      height: 2000,
      sections: 1,
      shelves: 4,
      drawer: "нет",
      set: "ригельный замок, фиксатор",
      addShelfPrice: 26,
      price: 211,
    },
    {
      model: "ШАМ-0.5",
      type: "бухгалтерский",
      depth: 500,
      width: 850,
      height: 930,
      sections: 1,
      shelves: 1,
      drawer: "нет",
      set: "ригельный замок, фиксатор",
      addShelfPrice: 25,
      price: 133,
    },
    {
      model: "ШАМ-0.5/400",
      type: "бухгалтерский",
      depth: 400,
      width: 850,
      height: 930,
      sections: 1,
      shelves: 1,
      drawer: "нет",
      set: "ригельный замок, фиксатор",
      addShelfPrice: 15,
      price: 122,
    },
    {
      model: "ШАМ-12",
      type: "бухгалтерский",
      depth: 500,
      width: 425,
      height: 1860,
      sections: 1,
      shelves: 3,
      drawer: "нет",
      set: "ригельный замок",
      addShelfPrice: 27,
      price: 124,
    },
    {
      model: "ШАМ-12/1320",
      type: "бухгалтерский",
      depth: 500,
      width: 425,
      height: 1320,
      sections: 1,
      shelves: 2,
      drawer: "нет",
      set: "ригельный замок",
      addShelfPrice: 28,
      price: 124,
    },
    {
      model: "ШАМ-12/680",
      type: "бухгалтерский",
      depth: 500,
      width: 425,
      height: 680,
      sections: 1,
      shelves: 1,
      drawer: "нет",
      set: "ригельный замок",
      addShelfPrice: 17,
      price: 111,
    },
    {
      model: "ШАМ-11.K",
      type: "бухгалтерский",
      depth: 450,
      width: 960,
      height: 1860,
      sections: 1,
      shelves: 3,
      drawer: "нет",
      set: "врезной замок повышенной секретности",
      addShelfPrice: 19,
      price: 112,
    },
    {
      model: "ШАМ-24.0",
      type: "бухгалтерский",
      depth: 500,
      width: 600,
      height: 1860,
      sections: 1,
      shelves: 4,
      drawer: "нет",
      set: "4 врезных замка. 4 полки",
      addShelfPrice: 20,
      price: 112,
    },
    {
      model: "КР-2",
      type: "картотечный",
      depth: 630,
      width: 465,
      height: 715,
      sections: 1,
      shelves: "нет",
      drawer: 2,
      set: "формат А4",
      addShelfPrice: 14,
      price: 100,
    },
    {
      model: "КР-3",
      type: "картотечный",
      depth: 630,
      width: 465,
      height: 1025,
      sections: 1,
      shelves: "нет",
      drawer: 3,
      set: "формат А4",
      addShelfPrice: 14,
      price: 101,
    },
    {
      model: "КР-4",
      type: "картотечный",
      depth: 630,
      width: 465,
      height: 1335,
      sections: 1,
      shelves: "нет",
      drawer: 4,
      set: "формат А4",
      addShelfPrice: 31,
      price: 101,
    },
    {
      model: "КР-5",
      type: "картотечный",
      depth: 630,
      width: 465,
      height: 1645,
      sections: 1,
      shelves: "нет",
      drawer: 5,
      set: "формат А4",
      addShelfPrice: 32,
      price: 104,
    },
    {
      model: "КР-7",
      type: "картотечный",
      depth: 585,
      width: 525,
      height: 1370,
      sections: 1,
      shelves: "нет",
      drawer: 7,
      set: "формат А5",
      addShelfPrice: 22,
      price: 121,
    },
  ],
  installation: {
    types: [
      { type: "self_install", name: "самостоятельная", price: 0 },
      {
        type: "build",
        name: "собрать стеллаж",
        price: 300,
      },
      {
        type: "build_fix",
        name: "собрать и закрепить к стене",
        price: 400,
      },
    ],
  },
  initialState: {
    items: {
      model: { value: "ШРМ-АК/500", active: "all" },
      type: { value: "для одежды", active: "all" },
      depth: { value: 500, active: "all" },
      width: { value: 500, active: "all" },
      height: { value: 1860, active: "all" },
      sections: { value: 2, active: "all" },
      shelves: { value: 2, active: "all" },
      drawer: { value: "нет", active: "all" },
      addShelfPrice: { value: 11 },
      set: {
        value: "2 перекладины, 4 крючка, 2 верзных замка",
        active: "all",
      },
    },
    itemsQnt: 1,
    addShelfPriceQnt: { value: 0, fullName: "items_addShelfPrice" },
    installation: "self_install",
    delivery: ["self_delivery"],
    total: 100,
  },
};
