export const metalCabinets = [
  {
    name: "Шкаф металлический для одежды ШРМ",
    titles: [
      { items_model: "Модель" },
      { items_depth: "Глубина, см" },
      { items_width: "Ширина, см" },
      { items_height: "Высота шкафа, см" },
      { items_sections: "Количество секций" },
      { items_shelves: "Количество полок" },
      { items_set: "Комплектация" },
    ],
    items: [
      {
        model: "ШРМ-АК/500",
        depth: 500,
        width: 500,
        height: 1860,
        sections: 2,
        shelves: 2,
        set: "2 перекладины, 4 крючка, 2 верзных замка",
        price: 100,
      },
      {
        model: "ШРМ-АК-У",
        depth: 500,
        width: 500,
        height: 1860,
        sections: 1,
        shelves: 3,
        set: "1 перекладина, 2 крючка, 1 верзной замок",
        price: 200,
      },
      {
        model: "ШРМ-АК",
        depth: 500,
        width: 600,
        height: 1860,
        sections: 2,
        shelves: 2,
        set: "2 перекладины, 4 крючка, 2 верзных замка",
        price: 300,
      },
      {
        model: "ШРМ-АК/800",
        depth: 500,
        width: 800,
        height: 1860,
        sections: 2,
        shelves: 2,
        set: "2 перекладины, 4 крючка, 2 верзных замка",
        price: 400,
      },
      {
        model: "ШРМ-22",
        depth: 500,
        width: 600,
        height: 1860,
        sections: 2,
        shelves: 2,
        set: "2 перекладины, 4 крючка, 2 верзных замка",
        price: 400,
      },
      {
        model: "ШРМ-22/800",
        depth: 500,
        width: 600,
        height: 1860,
        sections: 2,
        shelves: 2,
        set: "2 перекладины, 4 крючка, 2 верзных замка",
        price: 412,
      },
      {
        model: "ШРМ-33",
        depth: 500,
        width: 900,
        height: 1860,
        sections: 3,
        shelves: 3,
        set: "3 перекладины, 6 крючков, 3 верзных замка",
        price: 450,
      },
      {
        model: "ШРМ-11",
        depth: 500,
        width: 300,
        height: 1860,
        sections: 1,
        shelves: 1,
        set: "1 перекладина, 2 крючка, 1 верзной замок",
        price: 422,
      },
      {
        model: "ШРМ-11/400",
        depth: 500,
        width: 400,
        height: 1860,
        sections: 1,
        shelves: 1,
        set: "1 перекладина, 2 крючка, 1 верзной замок",
        price: 422,
      },
      {
        model: "ШРМ-12",
        depth: 500,
        width: 300,
        height: 1860,
        sections: "2 отделения",
        shelves: 1,
        set: "1 перекладина, 2 крючка, 1 верзной замок",
        price: 422,
      },
      {
        model: "ШРМ-22М",
        depth: 500,
        width: 600,
        height: 1860,
        sections: 2,
        shelves: 1,
        set: "2 перекладины, 4 крючка, 2 верзной замок",
        price: 422,
      },
      {
        model: "ШРМ-22М/800",
        depth: 500,
        width: 800,
        height: 1860,
        sections: 1,
        shelves: 1,
        set: "2 перекладины, 4 крючка, 2 верзной замок",
        price: 422,
      },
      {
        model: "ШРМ-М",
        depth: 500,
        width: 300,
        height: 1860,
        sections: 1,
        shelves: 1,
        set: "1 перекладина, 2 крючка, 1 верзной замок",
        price: 422,
      },
      {
        model: "ШРМ-М/400",
        depth: 500,
        width: 400,
        height: 1860,
        sections: 1,
        shelves: 1,
        set: "1 перекладина, 2 крючка, 1 верзной замок",
        price: 422,
      },
      {
        model: "ШРМ-21",
        depth: 500,
        width: 400,
        height: 1860,
        sections: "2 отделения",
        shelves: 1,
        set: "2 перекладины, 4 крючка, 1 верзной замок",
        price: 422,
      },
      {
        model: "ШРМ-22У",
        depth: 500,
        width: 600,
        height: 1860,
        sections: 2,
        shelves: 5,
        set:
          "в одной секции: полка для головного убора, 1 перекладина, 2 крючка, замок в другой 4 регулируемые полки, замок",
        price: 422,
      },
      {
        model: "ШРМ-22/800У",
        depth: 500,
        width: 800,
        height: 1860,
        sections: 2,
        shelves: 5,
        set:
          "в одной секции: полка для головного убора, 1 перекладина, 2 крючка, замок в другой 4 регулируемые полки, замок",
        price: 422,
      },
      {
        model: "ШРМ-24",
        depth: 500,
        width: 600,
        height: 1860,
        sections: "4 отделения",
        shelves: 1,
        set: "4 перекладины, 8 крючков, 4 верзных замка",
        price: 422,
      },
    ],
    initialState: {
      items: {
        depth: { value: 500, active: [500] },
        width: { value: 500, active: [500, 600, 800] },
        height: { value: 1860, active: [1860] },
        sections: { value: 2, active: [1, 2] },
        shelves: { value: 2, active: [2, 3] },
        set: "2 перекладины, 4 крючка, 2 верзных замка",
      },
      itemsQnt: 1,
      installation: "self_install",
      delivery: ["self_delivery"],
      total: 100,
    },
  },
  {
    name: "Шкаф металлический, бухгалтерский ШАМ-11",
    version: [
      {
        depth: 500,
        width: 850,
        height: 1860,
        sectionsQnt: 1,
        shelvesQnt: 1,
        price: 100,
      },
      {
        depth: 500,
        width: 850,
        height: 1860,
        sectionsQnt: 1,
        shelvesQnt: 3,
        price: 200,
      },
      {
        depth: 450,
        width: 920,
        height: 1860,
        sectionsQnt: 1,
        shelvesQnt: 3,
        price: 300,
      },
      {
        depth: 400,
        width: 850,
        height: 1860,
        sectionsQnt: 1,
        shelvesQnt: 3,
        price: 400,
      },
      {
        depth: 500,
        width: 850,
        height: 2000,
        sectionsQnt: 1,
        shelvesQnt: 4,
        price: 500,
      },
      {
        depth: 450,
        width: 960,
        height: 1860,
        sectionsQnt: 1,
        shelvesQnt: 3,
        price: 600,
      },
    ],
    initialState: {
      version: {
        depth: 500,
        width: 850,
        height: 1860,
        sectionsQnt: 1,
        shelvesQnt: 1,
      },
      installation: "self_install",
      delivery: "self_delivery",
      total: 100,
    },
  },
  {
    name: "Шкаф металлический, картотечный КР",
    version: [
      { depth: 630, width: 465, height: 715, drawerQnt: 2, price: 100 },
      { depth: 630, width: 465, height: 1025, drawerQnt: 3, price: 200 },
      { depth: 630, width: 465, height: 1335, drawerQnt: 4, price: 300 },
      { depth: 630, width: 465, height: 1645, drawerQnt: 5, price: 400 },
      { depth: 585, width: 525, height: 1370, drawerQnt: 7, price: 500 },
    ],
    initialState: {
      version: { depth: 630, width: 465, height: 715, drawerQnt: 2 },
      installation: "self_install",
      delivery: "self_delivery",

      total: 2720,
    },
  },
];
